on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST https://gh-branch-commits.rifkifauzi.id  --data "{'cache':'true'}" -H "Content-type:application/json"
